const TopRated= [
    {
        "id":'20',
        "title": "Jodhaa Akbar",
        "year": "2008",
        "genres": [
            "Action",
            "Adventure",
            "Biography"
        ],
        "ratings": [
            7,
            2,
            3,
            8,
            6,
            1,
            4,
            2,
            1,
            10,
            6,
            3,
            7,
            4,
            4,
            1,
            3,
            9,
            5,
            10,
            2,
            6,
            9,
            1,
            3,
            7,
            9,
            7,
            3,
            9
        ],
        "poster": "img/MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT213M",
        "releaseDate": "2008-02-15",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jodhaa Akbar is a sixteenth century love story about a marriage of alliance that gave birth to true love between a great Mughal Emperor, Akbar and a Rajput princess, Jodhaa. Politically, success knew no bounds for Emperor Akbar, After having secured the Hindu Kush, he furthered his realm by conquest until his empire extended from Afghanistan to the Bay of Bengal, and from the Himalayas to the Godhavari River. Through a shrewd blend of tolerance, generosity and force, Akbar won the allegiance of the Rajputs, the most belligerent Hindus. But little did Akbar know that when he married Jodhaa, a fiery Rajput princess, in order to further strengthen his relations with the Rajputs, he would in turn be embarking upon a new journey - the journey of true love. The daughter of King Bharmal of Amer, Jodhaa resented being reduced to a mere political pawn in this marriage of alliance, and Akbar's biggest challenge now did not merely lie in winning battles, but in winning the love of Jodhaa - a ...                Written by\nhEmRaJ (gavin_coolhgr@hotmail.com)",
        "actors": [
            "Hrithik Roshan",
            "Aishwarya Rai Bachchan",
            "Sonu Sood"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg"
    },
    {
        "id":'24',
        "title": "Wake Up Sid",
        "year": "2009",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            7,
            10,
            6,
            7,
            3,
            3,
            1,
            4,
            10,
            2,
            6,
            3,
            6,
            1,
            6,
            7,
            8,
            4,
            10,
            9,
            10,
            4,
            6,
            2,
            5,
            6,
            2,
            4
        ],
        "poster": "img/MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg",
        "contentRating": "",
        "duration": "PT138M",
        "releaseDate": "2009-10-02",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In Mumbai, Sid Mehra is, in the words of his father, an arrogant, spoiled brat. He lives with a doting mother, subservient brother, and a father who covers his expenses and credit card bills. Sid takes his college finals then starts work at his father's business; he lasts less than a week before walking out. At a graduation party, he meets Aisha, newly arrived from Calcutta and set on becoming a writer. He shows her the city and helps her refurbish a rented flat. He asks if she'd like to progress from friend to something more, but she says no: he lacks ambition and isn't her type. Will her words, his exam results, a confrontation with his parents, and a break with his friends be enough to wake Sid up?                Written by\n<jhailey@hotmail.com>",
        "actors": [
            "Ranbir Kapoor",
            "Konkona Sen Sharma",
            "Supriya Pathak"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg"
    },
    {
        "id":'25',
        "title": "Saala Khadoos",
        "year": "2016",
        "genres": [
            "Action",
            "Drama",
            "Sport"
        ],
        "ratings": [
            2,
            3,
            7,
            2,
            7,
            2,
            2,
            10,
            1,
            2,
            7,
            6,
            4,
            2,
            2,
            1,
            6,
            3,
            4,
            2,
            2,
            2,
            3,
            5,
            7,
            10,
            7,
            8,
            3,
            10
        ],
        "poster": "img/MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT109M",
        "releaseDate": "2016-01-29",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "An under-fire boxing coach, Prabhu is transferred from Hisar in Haryana to Chennai as his bosses at the Boxing Council do not like his disrespectful rule-breaking unconventional ways. In Chennai, he chances upon the raw fighting talent of Madhi, the sibling of aspiring boxer Lakshmi. He decides to put all his effort to tame Madhie and get her to shine but he is repeatedly put off by her playfulness & distrust.                Written by\nPipingHotViews",
        "actors": [
            "Madhavan",
            "Nassar",
            "Radha Ravi"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg"
    },
    {
        "id":'26',
        "title": "Qayamat Se Qayamat Tak",
        "year": "1988",
        "genres": [
            "Action",
            "Drama",
            "Musical"
        ],
        "ratings": [
            5,
            2,
            10,
            3,
            2,
            5,
            8,
            1,
            4,
            5,
            3,
            6,
            9,
            8,
            9,
            9,
            8,
            4,
            10,
            2,
            1,
            1,
            5,
            9,
            3,
            1,
            9,
            8,
            8,
            7
        ],
        "poster": "img/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg",
        "contentRating": "",
        "duration": "PT162M",
        "releaseDate": "1988-03-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Both Dhanraj Singh and Randhir Singh are two bitter and old time enemies. They faced a disastrous situation when there children, Raj and Rashmi falls deeply in love. They openly declares there hatred for one another and will do anything in there power even kill but they will not accept there children's choice. But Raj and Rashmi is dedicated to there love and is not willing to accept the fact that there dads are enemies.                Written by\ngAvInDrA (brave_loverboy2004@hotmail.com)",
        "actors": [
            "Aamir Khan",
            "Juhi Chawla",
            "Goga Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg"
    },
    {
        "id":'27',
        "title": "Delhi Belly",
        "year": "2011",
        "genres": [
            "Comedy",
            "Crime",
            "Drama"
        ],
        "ratings": [
            10,
            9,
            8,
            4,
            3,
            1,
            4,
            4,
            4,
            1,
            1,
            4,
            4,
            3,
            2,
            9,
            6,
            3,
            6,
            8,
            2,
            8,
            2,
            4,
            10,
            4,
            5,
            6,
            3,
            2
        ],
        "poster": "img/MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@._V1_SY360_SX250_AL_.jpg",
        "contentRating": "",
        "duration": "PT103M",
        "releaseDate": "2011-07-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Delhi-based Sonia agrees to deliver a package for Vladimir Dragunsky and asks her rather unkempt and debt-ridden fianc\u00e9, Tashi Malhotra, to do it for her. Tashi, in turn, asks one of two of his room-mates, Nitin. But Nitin forgets to do so due to an upset stomach ailment commonly known as 'Delhi Belly' as well as his plan to blackmail their landlord, Manish and asks the third roommate Arup to deliver the package. A gangster, Somayajulu, who was the recipient of this package, starts by brutally questioning Vladimir, and finds out that the package may be in the possession of the trio. While Tashi must deal with his attraction for Journalist Menaka and incur the wrath of her husband, Rajiv, he still has to fully come to terms whether or not he wants to marry Sonia. And the entry of ruthless Somayajulu and his gang seriously jeopardizes any plans Tashi and his friends may have for the future.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Imran Khan",
            "Vir Das",
            "Kunaal Roy Kapur"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@._V1_SY360_SX250_AL_.jpg"
    },
    {
        "id":'28',
        "title": "Magadheera",
        "year": "2009",
        "genres": [
            "Action",
            "Drama",
            "Romance"
        ],
        "ratings": [
            10,
            9,
            2,
            8,
            4,
            9,
            1,
            9,
            7,
            8,
            1,
            4,
            10,
            3,
            7,
            2,
            1,
            2,
            1,
            3,
            1,
            8,
            9,
            4,
            1,
            9,
            10,
            9,
            10,
            9
        ],
        "poster": "img/MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT147M",
        "releaseDate": "2009-07-30",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In 1609 AD, Mitravinda, a princess, and Kala Bhairava, the warrior that she loved, die. 400 years later, the warrior is reincarnated as Harsha, a motorcycle stuntman. He brushes hands with a girl and sparks fly as he begins to recall his past life. Knowing that he is destined to love this young woman, he sets about trying to identify her. Indu does not remember her past life and keeps Harsha at a distance; playing tricks on him until she gets to know him better. However, just as the two begin to fall in love, a sinister force from their shared past returns!                Written by\nL. Hamre",
        "actors": [
            "Kajal Aggarwal",
            "Dev Gill",
            "Srihari"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "id":'29',
        "title": "Highway",
        "year": "2014",
        "genres": [
            "Adventure",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            8,
            8,
            5,
            2,
            8,
            10,
            8,
            8,
            8,
            1,
            4,
            2,
            5,
            5,
            7,
            6,
            10,
            9,
            10,
            3,
            5,
            4,
            8,
            5,
            1,
            4,
            5,
            1
        ],
        "poster": "img/MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@._V1_SY500_CR0,0,344,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT133M",
        "releaseDate": "2014-02-21",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A city girl - young, full of life - is on the highway at night with her fianc\u00e9. Suddenly, her life is swung away from the brocade and jewelry of marriage to the harsh brutality of abduction. Her life will never be the same again. The gang is in a panic; the girl is a big industrialist's daughter, his links in the corridors of power make ransom out of the question. But for the leader of this group sending her back is not an option. As the days pass by, the scenery changes, the girl feels that she has changed as well. Gradually, a strange bond begins to develop between the victim and the oppressor. It is in this captivity that she, for the first time, feels free.                Written by\nVikram Nayak",
        "actors": [
            "Alia Bhatt",
            "Randeep Hooda",
            "Durgesh Kumar"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@._V1_SY500_CR0,0,344,500_AL_.jpg"
    },
    {
        "id":'20',
        "title": "Aankhen",
        "year": "2002",
        "genres": [
            "Comedy",
            "Thriller",
            "Crime"
        ],
        "ratings": [
            6,
            9,
            1,
            10,
            7,
            2,
            6,
            2,
            5,
            10,
            8,
            4,
            4,
            4,
            3,
            1,
            7,
            4,
            2,
            7,
            8,
            4,
            1,
            10,
            10,
            1,
            1,
            4,
            1,
            1
        ],
        "poster": "img/MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY500_SX345_AL_.jpg",
        "contentRating": "",
        "duration": "PT165M",
        "releaseDate": "2002-04-05",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Vijay Singh Rajput (Amitabh Bachchan) is a quirky manager of Vilasrao Jefferson Bank. He is extremely strict at work and believes in pushing his workers to the limit. This means that his superiors hold him in high regard for his unblemished reputation and excellent track record. But things go terribly wrong for the honest bank manager when he finds one of his own employees trying to con the customers. At this, he loses his temper and gets physical with the employee. This doesn't go down well with his superiors and they decide that Rajput is now a liability to the bank and they sack him. Amitabh can't believe the Board of Directors and his mind is filled with revenge and what better revenge than robbing the bank himself, ironic as it may sound. He decides that he must think of a plan that will hit the bank where it hurts the most - in its safe where all the money is kept. Rajput blackmails Neha (Sushmita Sen) to use her professional skills to help his plan, to train three blind men to ...                Written by\nAnonymous",
        "actors": [
            "Amitabh Bachchan",
            "Akshay Kumar",
            "Sushmita Sen"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY500_SX345_AL_.jpg"
    },
    {
        "id":'31',
        "title": "Rockstar",
        "year": "2011",
        "genres": [
            "Drama",
            "Music",
            "Musical"
        ],
        "ratings": [
            7,
            9,
            2,
            7,
            4,
            2,
            2,
            9,
            10,
            10,
            6,
            9,
            10,
            2,
            6,
            3,
            6,
            9,
            2,
            7,
            10,
            10,
            4,
            9,
            2,
            9,
            9,
            2,
            6,
            10
        ],
        "poster": "img/MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@._V1_SY500_SX375_AL_.jpg",
        "contentRating": "",
        "duration": "PT159M",
        "releaseDate": "2011-11-11",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The film follows Janardhan Jhakar in a series of flashbacks and flash forwards, how the small collage boy became an international rock sensation \"Jordan\". To chase his dreams of a rockstar, the wanna-be singer his counseled that music and feelings only come with pain. In the process of which, he meets Heer, a tough on the outside and popular college girl, the both become friends, and as time passes by his dreams of music fade away as they spend time together. When heer moves away, Janardhan is thrown out of his house because of family misunderstandings. As he bides his time at a local mosque, his passion for music comes back to life. He is soon signed by a record label, where he makes more enemies than friends, his tour takes him to Prague, where he is reunited with a married Heer. Things go awry when the two share an intimate moment, and Jordan his deported to India on trespassing charges filed by Heer's husband. Now an angry painful and lonely JORDAN embarks on his journey to become...                Written by\nEros International",
        "actors": [
            "Ranbir Kapoor",
            "Nargis Fakhri",
            "Shammi Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@._V1_SY500_SX375_AL_.jpg"
    }
]

export default TopRated